#this workflow is to deploy in all the environments
name: web-app-release
on:
  push:
    branches:
      - main
      - dev
      - qual
      - staging
  workflow_dispatch:

env:
  app_name: ${{ github.event.repository.name }}

jobs:
  # continuous-integration:
  #   uses: subramanya-au/build-repo/.github/workflows/build-image.yaml@main
  #   with:
  #     # IMAGE_NAME: ${{ github.event.repository.name }}
  #     repository: ${{ github.repository }}
  #   secrets:
  #     docker_username: ${{ secrets.DOCKER_USERNAME }}
  #     docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     github_pat: ${{ secrets.MY_PAT }}
  
  continuous-delivery-dev:
    uses: subramanya-au/k8s-manifests/.github/workflows/webapp.yaml@main
    # needs:
    #   - continuous-integration
    with:
      environment: dev
      app_name: ${{ github.event.repository.name }} 
    secrets:
      argocd_server: ${{ secrets.ARGOCD_SERVER }}
      argocd_username: ${{ secrets.ARGOCD_USERNAME }}
      argocd_password: ${{ secrets.ARGOCD_PASSWORD }}
      git_username: ${{ secrets.GIT_USERNAME }}
      github_pat: ${{ secrets.MY_PAT }}