#this workflow is to deploy in all the environments
name: web-app-release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-deployment:
    uses: subramanya-au/k8s-manifests/.github/workflows/webapp.yaml@main
    with:
      IMAGE_NAME: webapp
      repository: subramanya-au/webapp
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKERHUB_TOKEN }}
      github_pat: ${{ secrets.MY_PAT }}



