#this workflow is to deploy in all the environments
name: web-app-release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-out:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  continuous-deployment:
    uses: subramanya-au/k8s-manifests/.github/workflows/webapp.yaml@main

